name: Matthew Riddle
favicon: null
layout_spectrum: 0.66988
typography_spectrum: 0.6628299087751657
title: 'Digital Learning in Higher Education | Blog | Matthew D. Riddle'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.3398982137441635
  lightness: 0.24820828181691468
  saturation: 0.8162377958651632
  rhythmicContrast: 0.6070912696886808
purpose: []
